# Generated by Django 3.0.5 on 2020-04-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('ap', models.IntegerField()),
            ],
        ),
    ]
